name: PR Body Syncronizer

on:
    pull_request:
        types: [ synchronize, opened ]
    workflow_dispatch:

jobs:
  updateBody:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
                submodules: true

        - name: Extract branch name
          shell: bash
          run: echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          id: extract_branch                

        - name: 👓 read-yaml-file ${{ steps.extract_branch.outputs.BR_VERSION }}/config.yaml
          uses: pietrobolcato/action-read-yaml@1.1.0
          id: read_action_js
          with:
            config: ${{ github.workspace }}/${{ steps.extract_branch.outputs.BR_VERSION }}/config.yaml    

        - name: A/B Check
          if: ${{ steps.read_action_js.outputs.image == '' }}
          uses: actions/github-script@v7.0.1
          with:
            script: |
                core.setFailed('Image in yaml config of ${BR_VERSION} is not set!')

        - name: pull-request source ${{ steps.extract_branch.outputs.BR_VERSION }}
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          continue-on-error: true
          shell: bash
          run: |
            set -x
            git config --global user.email "workflow-bot@github.com"
            git config --global user.name "Prerelease Bot"
            git fetch origin master ${BRANCH_NAME}
            git log --no-merges --left-right --graph --cherry-pick --oneline origin/master...origin/${BRANCH_NAME} | gh pr edit ${{ github.event.pull_request.number }} --body-file -
