name: Docker Image CI - Build Release.

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #      - name: Publish Plex Addon
      #        uses: home-assistant/builder@master
      #        with:
      #          args: |
      #            --all \
      #            --docker-hub-check \
      #            --target addon-plex/plex \
      #            --docker-hub dianlight

      - name: Publish SambaNAS Addon
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --docker-hub-check \
            --target sambanas \
            --docker-hub dianlight

      - name: pull-request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        shell: bash
        run: |
          gh pr create --title "Releasing ${{ github.ref }} into master" --body ":crown: *An automated PR*" --fill
