name: Docker Image CI - PR Label to Release

on:
    pull_request:
        types: [ labeled ]
        branches: 
            - master

permissions:
  pull-requests: write

jobs:
    build:
        if: ${{ github.event.label.name == 'do_release' }}
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
                submodules: true

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
       
        - name: Extract branch name
          shell: bash
          run: echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          id: extract_branch
                
        - name: Publish ${{ steps.extract_branch.outputs.BR_VERSION }} Addon
          uses: home-assistant/builder@master
          env:
                CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
          with:
                args: |
                    --all \
                    --target ${{ steps.extract_branch.outputs.BR_VERSION }} \
                    --docker-hub dianlight
            

