name: Docker Image CI - Build Pre-Release

on:
  push:
    branches:
      - prerelease/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ✍🏼 version SambaNAs
        id: version_set
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./sambanas/config.yaml
          path: version
          set: .dev${{ github.run_number }}
          get: true
          append: true
          
      - name: Add and commit config
        shell: bash
        run: |
          git add ./sambanas/config.yaml
          git commit -m "Tag Prerelease Version"

      - name: Publish SambaNAS Addon ${{ steps.version_set.outputs.value_new }}
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight

#      - name: Extract branch name
#        shell: bash
#        run: echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
#        id: extract_branch

      - name: pull-request ${{ steps.version_set.outputs.value_old }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        shell: bash
        run: |
          gh pr create --base "release/${{ steps.version_set.outputs.value_old }}" --title "Releasing ${{ github.ref }} into release" --body ":crown: *An automated PR*"
#          gh pr create --base "release/${{ steps.extract_branch.outputs.BR_VERSION }}" --title "Releasing ${{ github.ref }} into release" --body ":crown: *An automated PR*"  

      - name: Create pull request for Beta Repository
        uses: 0xlino/action-pull-request-another-repo@main
        continue-on-error: true
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'sambanas'
          destination_repo: 'dianlight/hassio-addons-beta'
          #destination_folder: 'sambanas'
          destination_base_branch: 'master'
          destination_head_branch: 'prerelease'
          user_email: 'lucio.tarantino@gmail.com'
          user_name: 'dianlight'
          #pull_request_reviewers: 'reviewers'
          
