name: Docker Image CI - PR Label to Release

on:
    pull_request:
        types: [ synchronize, ready_for_review ]
        branches: 
            - master
    workflow_dispatch:

permissions:
  pull-requests: write

jobs:
    build:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish SambaNAS Addon
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight
