name: Docker Image CI - Build Pre-Release

on:
  push:
    branches:
      - prerelease/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: zsh
        run: |
           echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
           echo "BR_PROJECT=${${GITHUB_REF##*/}%%_*}"" >> "$GITHUB_OUTPUT"
          
        id: extract_branch

      - name: ‚úçüèº version ${{ steps.extract_branch.outputs.BR_PROJECT }}
        id: version_set
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./${{ steps.extract_branch.outputs.BR_PROJECT }}/config.yaml
          path: version
          set: .beta${{ github.run_number }}
          get: true
          append: true

      - name: ‚úçüèº BetaName ${{ steps.extract_branch.outputs.BR_PROJECT }}
        id: betaname_set
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./${{ steps.extract_branch.outputs.BR_PROJECT }}/config.yaml
          path: name
          set: -Œ≤
          get: true
          append: true
            
      - name: Publish ${{ steps.extract_branch.outputs.BR_PROJECT }} Addon ${{ steps.version_set.outputs.value_new }}
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target ${{ steps.extract_branch.outputs.BR_PROJECT }} \
            --docker-hub dianlight

      - name: Create pull request for Beta Repository ${{ steps.extract_branch.outputs.BR_PROJECT }}
        uses: thzois/autobot@v1.0.3
        continue-on-error: true
        env:
          GH_ACCESS_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          git_config_user_email: 'ffp-bot@github.com'
          git_config_user_name: 'ffp-bot'
          target_repo: 'dianlight/hassio-addons-beta'
          source_dir: '${{ steps.extract_branch.outputs.BR_PROJECT }}'
#          source_dir_copy_glob: '!(*.yaml)'
          target_dir: ''
          pr_target_repo_base_branch: 'master'
#          pr_target_repo_compare_branch: 'autobot/${{ steps.version_set.outputs.value_new }}'
#          pr_title: '[autobot] ${{ steps.version_set.outputs.value_new }} Automated changes'
#          pr_description_text: '[autobot] ${{ steps.version_set.outputs.value_new }} Automated changes'
          pr_label: 'autobot'

      - name: Restoring original repository
        shell: bash
        run: |
          git config --global user.email "workflow-bot@github.com"
          git config --global user.name "Prerelease Bot"
          git restore .
          git clean -f
          
      - name: pull-request ${{ steps.version_set.outputs.value_old }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        shell: bash
        run: |
          gh pr create --title "Releasing ${{ github.ref }}" --body ":exclamation: Set `do_release` label to enable merge! " --fill --draft  
#          gh pr create --base "release/${{ steps.extract_branch.outputs.BR_VERSION }}" --title "Releasing ${{ github.ref }} into release" --body ":crown: *An automated PR*"  

